/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_DoorLock_indication_SWC_.c
 * Generated on: Tue Feb 18 9:27:0 EET
 ********************************************************************/

#include "string.h"
#include "Rte_DoorLock_indication_SWC.h"
#include"Rte_DoorSensorAbstractionSWC.h"


// this should be defined in the other SWC to be global to other SWCs
Rte_DE_myuint8 DoorLock_indication_RP_SR_DoorState_DoorState;

Rte_DE_myuint8 ReadDoorSensor_PP_SR_DoorState;

const Rte_CDS_DoorLock_indication_SWC Rte_Instance_DoorLock_indication_SWC = {
&ReadDoorSensor_PP_SR_DoorState
};

const Rte_CDS_DoorLock_indication_SWC * const Rte_Inst_DoorLock_indication_SWC = &Rte_Instance_DoorLock_indication_SWC;


Std_ReturnType DoorLock_indication_SWC_RP_CS_Led_Switch_Led_Switch_Buffer_retcode = RTE_E_OK;

FunctionPtr_DoorLock_indication_SWC_RP_CS_Led_Switch_Led_Switch Rte_Call_DoorLock_indication_SWC_RP_CS_Led_Switch_Led_Switch_Delegate = 0;

myuint8 Rte_IRead_DoorLock_indication_SWC_DoorLock_indication_RP_SR_DoorState_DoorState (void)
{
	return (Rte_Inst_DoorLock_indication_SWC)->DoorLock_indication_RP_SR_DoorState_DoorState->value;
}


//ARUNIT is used to test every SWC independently So this is why it doesn't call the other runnables
Std_ReturnType Rte_Call_DoorLock_indication_SWC_RP_CS_Led_Switch_Led_Switch (myuint8 LedState)
{
	Std_ReturnType __result = DoorLock_indication_SWC_RP_CS_Led_Switch_Led_Switch_Buffer_retcode;
	if ( Rte_Call_DoorLock_indication_SWC_RP_CS_Led_Switch_Led_Switch_Delegate != 0 ) {
		__result = Rte_Call_DoorLock_indication_SWC_RP_CS_Led_Switch_Led_Switch_Delegate(LedState);
	}

	//Synch Implementation to call Direct runnable(operation)
	 Led_Switch_Runnable( LedState);

	//when we come to the OSEK part we will write code which will invoke the OS Alarm
	//OS Alarm will "operation invoked event" -> there will be extended task waiting on this event
	//when this event comes it will invoke the runnable of the operation LED_Switch
	return __result;
}
